"""empty message

Revision ID: e5953c542ec3
Revises: 0a78aa3098ee
Create Date: 2017-09-14 22:18:37.470069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5953c542ec3'
down_revision = '0a78aa3098ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comments_timpstamp', table_name='comments')
    op.drop_column('comments', 'timpstamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timpstamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_comments_timpstamp', 'comments', ['timpstamp'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
