"""empty message

Revision ID: ebda2d5ca8f8
Revises: 0a78aa3098ee
Create Date: 2017-09-17 22:30:01.982666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebda2d5ca8f8'
down_revision = '0a78aa3098ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'timpstamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timpstamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
